name: ML Scheduled Run

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    # Runs every Thursday at 6 AM (Sweden Time, which is UTC+2 during daylight saving)
    - cron: '0 4 * * 4'

jobs:
  run-ml:
    runs-on: ubuntu-latest

    steps:
    # Stop workflow after 25 May 2025
    - name: Check end date
      run: |
        current_date=$(date -u +"%Y-%m-%d")
        end_date="2025-05-25"
        if [[ "$current_date" > "$end_date" ]]; then
          echo "The workflow has reached its end date and will no longer run."
          exit 0
        fi

    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Miniconda
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.11
        auto-update-conda: true

    # Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        conda create --name venv_fpl_player_points python=3.11.5 -y
        conda run -n venv_fpl_player_points pip install -r requirements.txt

    # Run your script using 'conda run'
    - name: Run ML pipeline
      run: |
        conda run -n venv_fpl_player_points python main.py --part all --sample_fraction_grid_data 0.3 --n_random_hyperparameters 20 --run_grids --run_final_models

    # Upload predictions.csv as an artifact
    - name: Upload predictions
      uses: actions/upload-artifact@v4
      with:
        name: predictions
        path: artifacts/ml_results/predictions.csv
        